export const countries = [
    "Afghanistan",
    "Albania",
    "Algeria",
    "Andorra",
    "Angola",
    "Antigua và Barbuda",
    "Argentina",
    "Armenia",
    "Úc",
    "Áo",
    "Azerbaijan",
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Bỉ",
    "Belize",
    "Benin",
    "Bhutan",
    "Bolivia",
    "Bosnia và Herzegovina",
    "Botswana",
    "Brazil",
    "Brunei",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "Cabo Verde",
    "Campuchia",
    "Cameroon",
    "Canada",
    "Chad",
    "Chile",
    "Trung Quốc",
    "Colombia",
    "Comoros",
    "Congo",
    "Costa Rica",
    "Croatia",
    "Cuba",
    "Cyprus",
    "Cộng hòa Séc",
    "Đan Mạch",
    "Djibouti",
    "Dominica",
    "Cộng hòa Dominican",
    "Ecuador",
    "Ai Cập",
    "El Salvador",
    "Guinea Xích đạo",
    "Eritrea",
    "Estonia",
    "Eswatini",
    "Ethiopia",
    "Fiji",
    "Phần Lan",
    "Pháp",
    "Gabon",
    "Gambia",
    "Georgia",
    "Đức",
    "Ghana",
    "Hy Lạp",
    "Grenada",
    "Guatemala",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Honduras",
    "Hungary",
    "Iceland",
    "Ấn Độ",
    "Indonesia",
    "Iran",
    "Iraq",
    "Ireland",
    "Israel",
    "Ý",
    "Jamaica",
    "Nhật Bản",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kiribati",
    "Kuwait",
    "Kyrgyzstan",
    "Lào",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Quần đảo Marshall",
    "Mauritania",
    "Mauritius",
    "Mexico",
    "Micronesia",
    "Moldova",
    "Monaco",
    "Mông Cổ",
    "Montenegro",
    "Morocco",
    "Mozambique",
    "Myanmar",
    "Namibia",
    "Nauru",
    "Nepal",
    "Hà Lan",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "Triều Tiên",
    "Na Uy",
    "Oman",
    "Pakistan",
    "Palau",
    "Palestine",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Ba Lan",
    "Bồ Đào Nha",
    "Qatar",
    "Romania",
    "Nga",
    "Rwanda",
    "Saint Kitts và Nevis",
    "Saint Lucia",
    "Saint Vincent và Grenadines",
    "Samoa",
    "San Marino",
    "São Tomé và Príncipe",
    "Ả Rập Saudi",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Slovakia",
    "Slovenia",
    "Quần đảo Solomon",
    "Somalia",
    "Nam Phi",
    "Hàn Quốc",
    "Nam Sudan",
    "Tây Ban Nha",
    "Sri Lanka",
    "Sudan",
    "Suriname",
    "Thụy Điển",
    "Thụy Sĩ",
    "Syria",
    "Đài Loan",
    "Tajikistan",
    "Tanzania",
    "Thái Lan",
    "Đông Timor",
    "Togo",
    "Tonga",
    "Trinidad và Tobago",
    "Tunisia",
    "Thổ Nhĩ Kỳ",
    "Turkmenistan",
    "Tuvalu",
    "Uganda",
    "Ukraine",
    "Các Tiểu Vương quốc Ả Rập Thống nhất",
    "Vương quốc Anh",
    "Hoa Kỳ",
    "Uruguay",
    "Uzbekistan",
    "Vanuatu",
    "Vatican",
    "Venezuela",
    "Việt Nam",
    "Yemen",
    "Zambia",
    "Zimbabwe"
];